version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "RasyonetDbPassword123!"
    ports:
      - "1433:1433"

  api:
    build:
      context: ./FinancialTracker.API
      dockerfile: Dockerfile
    ports:
      - "7147:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=RasyonetTrackerDb;User Id=sa;Password=RasyonetDbPassword123!;TrustServerCertificate=True;
      # 1. ÇÖZÜM: Kaydetmeme sorununu çözen API şifresi (.env dosyasından okur)
      - Finnhub__ApiKey=${FINNHUB_API_KEY}

  mvc:
    build:
      context: ./FinancialTracker.MVC
      dockerfile: Dockerfile
    ports:
      - "7163:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ApiSettings__BaseUrl=http://api:8080/api/
      # 2. ÇÖZÜM: SignalR Kırmızı hatasını çözen dinamik adres
      - SignalRHubUrl=http://localhost:7147/hubs/dashboard


volumes:
  sql_data:
