name: CI/CD Pipeline to Plesk (FTP)

on:
  push:
    branches: [ "dev" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout Code
      uses: actions/checkout@v5

    - name: ⚙️ Setup .NET 10
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.0.x'

    - name: 🏗️ Publish API
      run: dotnet publish FinancialTracker.API/FinancialTracker.API.csproj -c Release -o ./publish/api

    - name: 🏗️ Publish MVC
      run: dotnet publish FinancialTracker.MVC/FinancialTracker.MVC.csproj -c Release -o ./publish/mvc

    - name: 🔐 Generate appsettings.Production.json for API
      env:
        PROD_DB_CONNECTION: ${{ secrets.PROD_DB_CONNECTION }}
        FINNHUB_API_KEY: ${{ secrets.FINNHUB_API_KEY }}
      run: |
        cat <<EOF > ./publish/api/appsettings.Production.json
        {
          "ConnectionStrings": {
            "DefaultConnection": "$PROD_DB_CONNECTION"
          },
          "FinnhubSettings": {
            "ApiKey": "$FINNHUB_API_KEY"
          }
        }
        EOF

    - name: 🛠️ Install LFTP (For Fast & Reliable FTP)
      run: sudo apt-get update && sudo apt-get install -y lftp

    - name: 🚀 Deploy API
      env:
        FTP_HOST: ${{ secrets.MY_FTP_HOST }}
        FTP_USER: ${{ secrets.MY_FTP_USER }}
        FTP_PASSWORD: ${{ secrets.MY_FTP_PASS }}
      run: |
        lftp -c "set ssl:verify-certificate no; open -u '$FTP_USER','$FTP_PASSWORD' '$FTP_HOST'; mirror -R -v --parallel=10 --exclude-glob appsettings.Development.json ./publish/api /api.rasyonet.com"

    - name: 🚀 Deploy MVC
      env:
        FTP_HOST: ${{ secrets.MY_FTP_HOST }}
        FTP_USER: ${{ secrets.MY_FTP_USER }}
        FTP_PASSWORD: ${{ secrets.MY_FTP_PASS }}
      run: |
        lftp -c "set ssl:verify-certificate no; open -u '$FTP_USER','$FTP_PASSWORD' '$FTP_HOST'; mirror -R -v --parallel=10 --exclude-glob appsettings.Development.json ./publish/mvc /httpdocs"